### ISSUE TITLE
Add Jokes part other than quotes

### ISSUE THREAD

**Issue by Jain-Sanchit** [Jain-Sanchit/webseries-quotes#3]
Make a new function for jokes part and a separate data file for jokes .
Add jokes too.

**Comment by RAJNEESH1708** [comment]
I want to contribute to this.

**Comment by cainwatson** [comment]
@Jain-Sanchit I can take this on

**Comment by Jain-Sanchit** [comment]
@cainwatson  Yes , Sure you can go with it . Keep me updated.

**Comment by cainwatson** [comment]
@Jain-Sanchit PR up

**Comment by Jain-Sanchit** [comment]
@cainwatson , Let me check and get back to you.

**Comment by Jain-Sanchit** [comment]
@cainwatson I have merged the PR , thanks for contributing.
